name: Terraform GCE Deploy

on:
  push:
    branches:
      - feature/suresh

permissions:
  contents: read
  id-token: write   # REQUIRED for Workload Identity Federation

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 🔐 Authenticate to GCP using WIF (OIDC)
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/629423970153/locations/global/workloadIdentityPools/gce-wif/providers/github
          service_account: sa-gce@hip-runner-477914-h3.iam.gserviceaccount.com

      # ☁️ Install gcloud (recommended)
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # 📦 Install Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # 🔍 Terraform Init
      - name: Terraform Init
        run: terraform init

      # 📋 Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 🧪 Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # 🚀 Terraform Apply
      # - name: Terraform Apply
      #   run: terraform apply -auto-approve

      # 🚀 Terraform Destroy
       - name: Terraform destroy
         run: terraform destroy -auto-approve
